import AppShell from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BarChart3, BookOpen, CheckCircle2, Loader2, Search, Shield, Users } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Admin() {
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const [search, setSearch] = useState("");
  const enabled = user?.role === "admin";
  const statsQuery = trpc.devotional.admin.stats.useQuery(undefined, { enabled });
  const listQuery = trpc.devotional.admin.list.useQuery(undefined, { enabled });
  const publishMutation = trpc.devotional.admin.publish.useMutation({ onSuccess: () => { utils.devotional.admin.list.invalidate(); toast.success("Status de publicação atualizado."); } });
  if (loading) return <AppShell><div className="flex min-h-[70vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-[#b38c31]" /></div></AppShell>;
  if (!enabled) return <AppShell><div className="mx-auto max-w-2xl px-4 py-24 text-center"><Shield className="mx-auto h-8 w-8 text-[#b38c31]" /><h1 className="mt-5 font-serif text-3xl">Área administrativa protegida.</h1><p className="mt-3 text-sm text-[#718077]">O acesso é definido pela função de administrador da conta.</p></div></AppShell>;
  const stats = statsQuery.data; const items = (listQuery.data ?? []).filter(item => `${item.title} ${item.theme} ${item.bibleReference}`.toLowerCase().includes(search.toLowerCase()));
  return <AppShell><div className="mx-auto max-w-[1200px] px-4 py-7 sm:px-7 lg:py-10"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-[#a07c34]"><Shield className="h-3.5 w-3.5" /> Administração</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-serif text-4xl font-semibold tracking-tight">Centro editorial</h1><p className="mt-2 text-sm text-[#718077]">Acompanhe a jornada e cuide do catálogo de devocionais.</p></div><Button className="rounded-xl bg-[#102820] text-white" onClick={() => toast.message("A criação de conteúdo está disponível pelo procedimento editorial seguro; o editor completo pode ser conectado nesta tela na próxima versão.")}>Novo devocional</Button></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Users />} label="Usuários cadastrados" value={stats?.users ?? 0} /><Metric icon={<Users />} label="Usuários ativos" value={stats?.activeUsers ?? 0} /><Metric icon={<CheckCircle2 />} label="Minutos concluídos" value={stats?.completions ?? 0} /><Metric icon={<BarChart3 />} label="Taxa de conclusão" value={`${stats?.completionRate ?? 0}%`} /></section>
    <section className="mt-8 rounded-[24px] border border-[#e5dfd1] bg-[#fffdfa] p-5 dark:border-white/10 dark:bg-[#17231f]"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-serif text-2xl font-semibold">Biblioteca de devocionais</h2><p className="mt-1 text-sm text-[#75827a]">{items.length} itens encontrados</p></div><div className="relative w-full sm:w-80"><Search className="absolute left-3 top-3 h-4 w-4 text-[#849087]" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar conteúdo..." className="h-10 rounded-xl border-[#ded7c8] bg-white pl-9 dark:border-white/10 dark:bg-white/5" /></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-y border-[#eae4d8] text-[10px] uppercase tracking-[.13em] text-[#7f8b82] dark:border-white/10"><tr><th className="py-3 font-semibold">Dia</th><th className="py-3 font-semibold">Devocional</th><th className="py-3 font-semibold">Referência</th><th className="py-3 font-semibold">Status</th><th className="py-3 text-right font-semibold">Ação</th></tr></thead><tbody>{items.map(item => <tr key={item.id} className="border-b border-[#f0ece3] last:border-0 dark:border-white/5"><td className="py-3 font-medium text-[#77847c]">{item.dayNumber}</td><td className="py-3"><span className="block font-semibold">{item.title}</span><span className="mt-0.5 block text-xs text-[#819087]">{item.theme}</span></td><td className="py-3 text-[#718077]">{item.bibleReference} · NVI</td><td className="py-3"><Badge className={item.published ? "bg-[#e1f0e2] text-[#326845] hover:bg-[#e1f0e2]" : "bg-[#eeeae1] text-[#7d7a70] hover:bg-[#eeeae1]"}>{item.published ? "publicado" : "rascunho"}</Badge></td><td className="py-3 text-right"><Button variant="ghost" size="sm" className="text-xs text-[#56775c]" onClick={() => publishMutation.mutate({ id: item.id, published: !item.published })}>{item.published ? "Despublicar" : "Publicar"}</Button></td></tr>)}</tbody></table></div></section></div></AppShell>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number }) { return <div className="rounded-2xl border border-[#e5dfd1] bg-white/75 p-5 dark:border-white/10 dark:bg-white/[.03]"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#edf3eb] text-[#416e53] dark:bg-[#294132]">{icon}</div><p className="mt-4 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-[#7c887f]">{label}</p></div>; }
