import AppShell from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BookOpen, Loader2, NotebookPen, Search, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

export default function Journal() {
  const { isAuthenticated } = useAuth();
  const [search, setSearch] = useState("");
  const stateQuery = trpc.devotional.state.useQuery(undefined, { enabled: isAuthenticated });
  if (!isAuthenticated) return <AppShell><div className="mx-auto max-w-2xl px-4 py-24 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#e7f0f8] text-[#3f6e8f]"><NotebookPen className="h-6 w-6" /></span><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-[#a07c34]">Meu Diário</p><h1 className="mt-3 font-serif text-4xl font-semibold">Guarde o que Deus está formando em você.</h1><p className="mx-auto mt-4 max-w-lg text-sm leading-6 text-[#718291]">Entre para registrar suas respostas, orações e aprendizados de cada devocional.</p><Button onClick={startLogin} className="mt-7 rounded-xl bg-[#102a43] text-white">Entrar para começar</Button></div></AppShell>;
  if (stateQuery.isLoading) return <AppShell><div className="flex min-h-[70vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-[#b38c31]" /></div></AppShell>;
  const entries = (stateQuery.data?.entries ?? []).filter(entry => `${entry.title} ${entry.theme} ${entry.content}`.toLowerCase().includes(search.toLowerCase()));
  return <AppShell><div className="mx-auto max-w-4xl px-4 py-7 sm:px-7 lg:py-10"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-[#a07c34]"><Sparkles className="h-3.5 w-3.5" /> Meu Diário</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight">Suas reflexões, em um só lugar.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#6d7b72]">Revisite aquilo que você discerniu em cada etapa da jornada.</p><div className="relative mt-7 max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-[#829087]" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Pesquisar no meu diário..." className="h-10 rounded-xl border-[#ddd7c9] bg-white pl-9 dark:border-white/10 dark:bg-white/5" /></div><section className="mt-7 space-y-4">{entries.map(entry => <article key={entry.id} className="rounded-2xl border border-[#e5dfd1] bg-[#ffffff] p-5 dark:border-white/10 dark:bg-[#15263b]"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#a58137]">Dia {entry.dayNumber} · {entry.theme}</p><h2 className="mt-1 font-serif text-xl font-semibold">{entry.title}</h2></div><Link href={`/devocional/${entry.dayNumber}`} className="rounded-lg bg-[#e8f0f5] px-3 py-1.5 text-xs font-semibold text-[#3c6c49] dark:bg-[#294132] dark:text-[#cbe2cd]">Abrir dia</Link></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-[#526259] dark:text-[#c6d2ca]">{entry.content}</p><p className="mt-4 border-t border-[#ece6d9] pt-3 text-[11px] text-[#89948c]">Atualizado em {new Date(entry.updatedAt).toLocaleDateString("pt-BR", { day: "2-digit", month: "short", year: "numeric" })}</p></article>)}</section>{entries.length === 0 && <div className="mt-10 rounded-[24px] border border-dashed border-[#d8d0bf] bg-[#ffffff]/60 p-12 text-center dark:border-white/10 dark:bg-white/[.02]"><BookOpen className="mx-auto h-6 w-6 text-[#b38c31]" /><h2 className="mt-4 font-serif text-2xl">Seu diário ainda está em branco.</h2><p className="mt-2 text-sm text-[#75827a]">Quando responder à pergunta de um devocional, suas palavras aparecerão aqui.</p><Link href="/" className="mt-5 inline-block text-sm font-semibold text-[#2f5d7c]">Ir para o devocional de hoje</Link></div>}</div></AppShell>;
}
