import AppShell from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { getBibleTranslation } from "@shared/bible-translations";
import { Check, Circle, Clock3, Flame, Loader2, Search, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

function dayOfYear() { const today = new Date(); return Math.floor((today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000); }
function streak(ids: number[]) { const done = new Set(ids); let count = 0; for (let day = dayOfYear(); day >= 1 && done.has(day); day -= 1) count += 1; return count; }

export default function Journey() {
  const { isAuthenticated } = useAuth();
  const [search, setSearch] = useState("");
  const currentDay = dayOfYear();
  const listInput = useMemo(() => ({ search: search.trim() || undefined }), [search]);
  const listQuery = trpc.devotional.list.useQuery(listInput);
  const stateQuery = trpc.devotional.state.useQuery(undefined, { enabled: isAuthenticated });
  const devotionals = listQuery.data ?? [];
  const completeDays = stateQuery.data?.completedDays ?? stateQuery.data?.completedIds ?? [];
  const completeSet = new Set(completeDays);
  const completedCount = completeDays.length;
  const progress = Math.round((completedCount / 365) * 100);
  const months = Array.from(new Set(devotionals.map(item => item.month)));
  const [activeMonth, setActiveMonth] = useState("Todos");
  const filtered = activeMonth === "Todos" ? devotionals : devotionals.filter(item => item.month === activeMonth);
  if (listQuery.isLoading || (isAuthenticated && stateQuery.isLoading)) return <AppShell><div className="flex min-h-[70vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-[#b38c31]" /></div></AppShell>;
  return <AppShell><div className="mx-auto max-w-[1420px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-[#a07c34]"><Sparkles className="h-3.5 w-3.5" /> Minha Jornada</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight">365 dias para construir com propósito.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#6e7d74]">Acompanhe sua constância, retome leituras e encontre o tema certo para a estação que está vivendo.</p></div><div className="rounded-2xl border border-[#e5dfd1] bg-white/70 px-5 py-4 dark:border-white/10 dark:bg-white/[.03]"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#857a67]">Seu progresso</p><div className="mt-1 flex items-baseline gap-2"><strong className="font-serif text-3xl">{completedCount}<span className="text-base font-normal text-[#869087]"> / 365</span></strong><span className="text-sm text-[#967934]">{progress}%</span></div></div></section>
    <section className="mt-8 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-[26px] bg-[#102820] p-6 text-white sm:p-7"><div className="flex justify-between gap-5"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#d9b45e]">Constância</p><p className="mt-2 font-serif text-2xl">Mais um dia caminhando com propósito.</p></div><Flame className="h-6 w-6 text-[#d9b45e]" /></div><div className="mt-7"><div className="mb-2 flex justify-between text-xs text-[#b9c9bf]"><span>Progresso anual</span><span>{progress}%</span></div><Progress value={progress} className="h-2 bg-white/15 [&>div]:bg-[#d9b45e]" /></div><div className="mt-6 grid grid-cols-3 gap-3 text-center"><div><strong className="block font-serif text-2xl">{streak(completeDays)}</strong><span className="text-[10px] uppercase tracking-wide text-[#9cafa4]">Sequência atual</span></div><div className="border-x border-white/10"><strong className="block font-serif text-2xl">{completedCount}</strong><span className="text-[10px] uppercase tracking-wide text-[#9cafa4]">Concluídos</span></div><div><strong className="block font-serif text-2xl">{365 - completedCount}</strong><span className="text-[10px] uppercase tracking-wide text-[#9cafa4]">Restantes</span></div></div></div>
      <div className="rounded-[26px] border border-[#e5dfd1] bg-[#fffdfa] p-6 dark:border-white/10 dark:bg-[#17231f]"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#9a7730]">Visão anual</p><div className="mt-5 grid grid-cols-31 gap-1">{Array.from({ length: 365 }, (_, index) => { const number = index + 1; const finished = completeSet.has(number); const today = number === currentDay; return <Link key={number} href={`/devocional/${number}`} title={`Dia ${number}`} className={finished ? "h-2.5 rounded-[3px] bg-[#487a57]" : today ? "h-2.5 rounded-[3px] bg-[#d9b45e] ring-2 ring-[#d9b45e]/30" : "h-2.5 rounded-[3px] bg-[#e6e3d9] dark:bg-white/10"} />; })}</div><div className="mt-5 flex gap-4 text-[10px] text-[#7b877f]"><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-sm bg-[#487a57]" /> concluído</span><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-sm bg-[#d9b45e]" /> hoje</span><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-sm bg-[#e6e3d9] dark:bg-white/10" /> próximo</span></div></div></section>
    <section className="mt-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="relative w-full lg:max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-[#849087]" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar por medo, liderança, referência..." className="h-10 rounded-xl border-[#ddd7c9] bg-white pl-9 dark:border-white/10 dark:bg-white/5" /></div><div className="flex max-w-full gap-2 overflow-x-auto pb-1">{["Todos", ...months].map(month => <button key={month} onClick={() => setActiveMonth(month)} className={activeMonth === month ? "whitespace-nowrap rounded-full bg-[#102820] px-3 py-1.5 text-xs font-semibold text-white" : "whitespace-nowrap rounded-full bg-[#e9e7df] px-3 py-1.5 text-xs font-semibold text-[#66756c] dark:bg-white/10 dark:text-[#cbd6ce]"}>{month}</button>)}</div></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(item => { const done = completeSet.has(item.dayNumber); const current = item.dayNumber === currentDay; const bibleTranslation = getBibleTranslation(item.bibleTranslation); return <Link key={item.dayNumber} href={`/devocional/${item.dayNumber}`} className="group rounded-2xl border border-[#e5dfd1] bg-white/75 p-4 transition-all hover:-translate-y-0.5 hover:shadow-md dark:border-white/10 dark:bg-white/[.03]"><div className="flex items-center justify-between"><span className={done ? "flex h-7 w-7 items-center justify-center rounded-full bg-[#dcecdf] text-[#397048]" : current ? "flex h-7 w-7 items-center justify-center rounded-full bg-[#f5e5b9] text-[#92702b]" : "flex h-7 w-7 items-center justify-center rounded-full bg-[#efeee9] text-[#77857d] dark:bg-white/10"}>{done ? <Check className="h-4 w-4" /> : <span className="text-[11px] font-bold">{item.dayNumber}</span>}</span><Badge variant="outline" className="border-[#ded7c8] text-[10px] font-medium text-[#78857d]">{done ? "concluído" : current ? "hoje" : "não iniciado"}</Badge></div><p className="mt-4 text-[10px] font-bold uppercase tracking-[.14em] text-[#a58137]">{item.theme}</p><h3 className="mt-1 font-serif text-lg font-semibold leading-6 group-hover:text-[#356248]">{item.title}</h3><p className="mt-2 flex items-center gap-1.5 text-xs text-[#7d897f]"><Clock3 className="h-3 w-3" /> {item.bibleReference} · {bibleTranslation.shortLabel}</p></Link>; })}</div>{filtered.length === 0 && <div className="mt-10 rounded-2xl border border-dashed border-[#d7cfbe] p-12 text-center text-sm text-[#7d897f]">Nenhum devocional encontrado. Tente um tema, título ou referência diferente.</div>}</section>
  </div></AppShell>;
}
